spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: COUNTRY-API
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/countries_api
    driverClassName: org.postgresql.Driver
    username: postgres
    password: pass
    hikari:
      auto_commit: false
logging:
  level.*:
    org.springframework.web.client.RestTemplate: INFO
    com.com.countries_api: debug
    org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor: TRACE

  file:
    name: logs/countries-api.log

server:
  port: 9972

